get providers form a category API
noggalito/porttare-backend pull request #28
Opened 2016-09-14 17:04 UTC by leninkp

@macool, @fabricioflores

2016-09-15 06:49 UTC, fabricioflores commented on app/controllers/api/categories_controller.rb
> +    def get_providers
no se si :macool: `semánticamente` sería mejor que providers sea un ruta dentro de categorías... y la llamada sea `categories/:id/providers`

2016-09-15 14:25 UTC, leninkp commented on app/controllers/api/categories_controller.rb
> +    def get_providers
ok, voy a cambiar el nombre de la ruta

2016-09-15 14:26 UTC, macool commented on app/controllers/api/categories_controller.rb
> +      })
buena estuvo.. pero estamos utilizando .json.jbuilder para intentar mantener un "estándar". más adelante las categorías, los proveedores tendrán atributos _privados_ que no queremos enviar mediante el API

https://github.com/noggalito/porttare-backend/blob/master/app/views/api/locations/previous_locations.json.jbuilder
https://github.com/rails/jbuilder

2016-09-15 14:27 UTC, macool commented on app/controllers/api/categories_controller.rb
> +      })
y lo mejor es tener un template por recurso. p ej. tú también renderizarías https://github.com/noggalito/porttare-backend/blob/master/app/views/api/categories/_category.json.jbuilder

2016-09-15 14:28 UTC, macool commented on config/routes.rb
> +      get 'get_providers'
sí, para la ruta hacer algo como resources :providers y tener un controlador propio para proveedores :allthethings:

2016-09-15 14:29 UTC, macool commented on app/controllers/api/categories_controller.rb
> +      "categories":[
me parece que apipie muestra este espacio en blanco cuando renderiza? lo probaste?

2016-09-15 15:00 UTC, leninkp commented on config/routes.rb
> +      get 'get_providers'
Al crear este nuevo controlador @macool como deberíamos manejar la ruta para obtener los proveedores de una categoria?
`providers/category/:id`

2016-09-15 15:18 UTC, leninkp commented on app/controllers/api/categories_controller.rb
> +      "categories":[
acabo de revisar, se esta mostrando mal, lo voy a corregir

2016-09-15 16:26 UTC, macool commented on config/routes.rb
> +      get 'get_providers'
no estoy seguro pero aquí haz `resource :providers, only: :show` (resource sin "s") y mira las rutas que te da

o (tal vez mejor)
`resources :providers, only: :index`

2016-09-16 01:59 UTC, leninkp commented on config/routes.rb
> +      get 'get_providers'
Queremos obtener: todos proveedores pertenecientes a una categoria, al crear la ruta con `resources :providers, only: :index`, la ruta generada es:
`/api/providers(.:format)`
como pasaria el id de la categoria? :philosoraptor:

2016-09-16 02:10 UTC, leninkp commented on config/routes.rb
> +      get 'get_providers'
o te referias a crear la ruta dentro de categories?
 `resources :categories, only: :index do`
      `resources :providers, only: :index`
    `end`
para obtener:
`/api/categories/:category_id/providers`

2016-09-16 15:24 UTC, leninkp commented
He actualizado el PR, listo para que lo revisen
@macool @fabricioflores

2016-09-19 15:40 UTC, macool commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
ya existe un partial para category, no?

2016-09-19 15:40 UTC, macool commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
https://github.com/noggalito/porttare-backend/blob/master/app/views/api/categories/_category.json.jbuilder

2016-09-19 15:41 UTC, macool commented on app/views/api/providers/index.json.jbuilder
> +json.providers @category.provider_profiles, :id, :razon_social
y esto es lo mismo que está en el otro template.. asumo que esto va a ser un nuevo template, ya que tiene que serializar también otras cosas como horarios de atención, etc.

2016-09-19 15:41 UTC, macool commented on app/views/api/providers/index.json.jbuilder
> +json.providers @category.provider_profiles, :id, :razon_social
en fin, los proveedores con un nuevo template para este endpoint

2016-09-19 15:42 UTC, macool requested changes

2016-09-19 15:42 UTC, macool commented on app/controllers/api/providers_controller.rb
> +
whitespace

2016-09-19 15:42 UTC, macool commented on app/controllers/api/categories_controller.rb
> +
no necesitamos esta línea en blanco

2016-09-20 02:33 UTC, leninkp commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
debería reutilizar `_category.json.jbuilder`?
estoy obteniendo desde el controlado `@category` y en `_category.json.jbuilder`  estamos usando `category`

2016-09-20 11:45 UTC, macool commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
@leninkp y para qué estás pasando `as: :provider`?

2016-09-20 11:45 UTC, macool requested changes

2016-09-20 14:14 UTC, leninkp commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
porque cree otro template donde se define que propiedades vamos a extraer de proveedor
``json.array!(``
    ``@category.provider_profiles,``
   `` partial: "provider",``
   `` as: :provider``
 `` )``

2016-09-20 14:15 UTC, macool commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
pasas `as: :category`. lee la documentación por favor

2016-09-20 14:16 UTC, macool commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
https://github.com/rails/jbuilder

2016-09-20 14:19 UTC, leninkp commented on app/views/api/providers/index.json.jbuilder
> +    :descripcion
``json.comments @post.comments, partial: 'comments/comment', as: :comment``
en este ejemplo lo pasa como ``as: :comment``

2016-09-20 18:01 UTC, merged